### ISSUE TITLE
Error to access jar file

### ISSUE THREAD

**Issue by Mondalgithub** [photon-lang/photon-compiler#12]
- [ ] Beta 0.1?
- [ ] Beta 0.1.6?
- [x] Beta 0.1.7?
![Screenshot_2020-04-13_12-48-40](https://user-images.githubusercontent.com/63331895/79101453-25b61100-7d86-11ea-9f4f-407a40657477.png)

Bug Trace Output:
Error: Unable to access jarfile photon-compiler-0.1.7-beta.jar

PDB:
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10
- [ ] 11

Please add Beta 0.2 Milestone to this issue.

**Comment by ChlorinePentoxide** [comment]
~ File not found
